### ISSUE TITLE
Return empty array for incorrect get query

### ISSUE THREAD

**Issue by ofuochi** [ofuochi/node-typescript-boilerplate#18]
I have an endpoint that is used to get a list of tenants by a query like so `.../api/v1/tenants?name=default` [here](https://github.com/ofuochi/node-typescript-boilerplate/blob/8b2ec70e6eeb67a62c77e7549f260888359ae322/src/ui/api/controllers/tenant_controller.ts#L24). I want the user to get an empty list if they queried for a nonexisting tenant name. 
Also if a client has passed in an unexpected get query, an empty array should be returned. `.../api/v1/tenants?name="blahblah"` should return an empty array.

**Comment by manAbl** [comment]
I think I can handle this

**Comment by ofuochi** [comment]
Please feel free. Thank you so much

**Comment by manAbl** [comment]
Having trouble initiating the app. It has several errors that don't let me start the development server

**Comment by ofuochi** [comment]
Can you share the error?

**Comment by manAbl** [comment]
This are the first ones:
-------------------------------------------------------------------
![Captura](https://user-images.githubusercontent.com/34801587/66089438-e12efa80-e544-11e9-9283-1e427cb4144c.JPG)

After "solving" each one:

![Captura](https://user-images.githubusercontent.com/34801587/66089569-8d70e100-e545-11e9-9555-b49cd3612f0c.JPG)

![Captura1](https://user-images.githubusercontent.com/34801587/66089571-8f3aa480-e545-11e9-88cd-1b9f33a12c11.JPG)



Others appear:
-------------------------------------------------------------------------
![Captura](https://user-images.githubusercontent.com/34801587/66089625-b6917180-e545-11e9-9c09-a553b450f645.JPG)

**Comment by ofuochi** [comment]
I'll fix this now! It could not resolve the relative path

**Comment by manAbl** [comment]
Tell me when is done :)

**Comment by ofuochi** [comment]
It's done.

**Comment by louisgjohnson** [comment]
opened a PR for this issue
