### ISSUE TITLE
Add useful methods to entities

### ISSUE THREAD

**Issue by ofuochi** [ofuochi/node-typescript-boilerplate#21]
Currently, in the `User` and `Tenant` entities, which are children of the `BaseEntity` there are a few methods for setting certain properties such as `setRole()` (in the `User` entity), `deactive()` (in the `BaseEntity`).
It will be useful to have more of these methods that directly modifies the entity

**Comment by rugglcon** [comment]
I can start working on this.

**Comment by ofuochi** [comment]
Please fell free
