### ISSUE TITLE
[Automapper] Breaking change in next version

### ISSUE THREAD

**Issue by nartc** [ofuochi/node-typescript-boilerplate#63]
## Question

Hi, I am the author of `automapper-nartc`. Due to allowing consumers creating different instances of AutoMapper (and making sure profiles/mappings still work with each instance), breaking changes have emerged. Specifically the `MappingProfileBase.configure()` method has changed. 

Now whenever you call `addProfile()` on the `AutoMapper` instance, that instance will be pass in the `configure()` method. `profile.configure(this)`.

```ts
const SomeProfile extends MappingProfileBase {
      constructor() {
         super();
      }

      configure(mapper: AutoMapper) {
         // use mapper.createMap() instead of this.createMap()
         mapper.createMap(...)
      }
}
```

Thanks for trying out the library.

**Comment by ofuochi** [comment]
@nartc thanks for the heads up. I'll implement the change
